spring:
    application:
        name: mkdata-invoices-collector

    data:
        mongodb:
            uri: ${MONGO_URI}

server:
    port: 8082
logging:
    level:
        org:
            springframework:
                data:
                    mongodb: DEBUG
