spring:
    application:
        name: mkdata-invoices-collector

    data:
        mongodb:
            uri: ${MONGO_URI}


server:
    port: 8083
logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG
